USE honeydo_helper_db;
INSERT INTO users (first_name, last_name, email, password, is_admin) VALUES
       ('Gage', 'Jackson', 'gage47@gmail.com', 'P@ssw0rd!', 0),
       ('Alice', 'Johnson', 'alice24@gmail.com', '3ncRyp7!', 0),
       ('Bob', 'Smith', 'bob42@gmail.com', 'P1zz@Pie', 0),
       ('Carol', 'Taylor', 'carol33@gmail.com', 'bR34kf@5t', 0),
       ('Dan', 'Thomas', 'dan18@gmail.com', 'W1nt3r1sH3r3', 0),
       ('Eve', 'Miller', 'eve29@gmail.com', 'SuMm3rSun', 0),
       ('Frank', 'Williams', 'frank54@gmail.com', 'AuTuMnL3av35', 0),
       ('Grace', 'Brown', 'grace11@gmail.com', 'SpR1nGR41n', 0),
       ('Hank', 'Davis', 'hank62@gmail.com', 'Sn0wFl@k3', 0),
       ('Irene', 'Wilson', 'irene21@gmail.com', 'H0tCh0c0', 0),
       ('Jack', 'Moore', 'jack31@gmail.com', 'B3achLif3', 0),
       ('Kira', 'Taylor', 'kira47@gmail.com', 'SunS3tDr34m', 0),
       ('Liam', 'Anderson', 'liam38@gmail.com', 'M00nl1ght', 0),
       ('Molly', 'Thomas', 'molly15@gmail.com', 'St@rG4z3', 0),
       ('Nathan', 'Jackson', 'nathan44@gmail.com', 'D@ydr34m', 0),
       ('Olivia', 'White', 'olivia32@gmail.com', 'N1ghtSkY', 0),
       ('Paul', 'Harris', 'paul39@gmail.com', 'M0rn1ngD3w', 0),
       ('Quincy', 'Martin', 'quincy27@gmail.com', 'Ev3n1ngM1st', 0),
       ('Rita', 'Thompson', 'rita16@gmail.com', 'R41nb0w', 0),
       ('Sam', 'Garcia', 'sam56@gmail.com', 'Cl0ud9', 0),
       ('Tina', 'Martinez', 'tina45@gmail.com', 'SunnyD4y', 0),
       ('Ursula', 'Robinson', 'ursula14@gmail.com', 'St0rmYn1ght', 0),
       ('Victor', 'Clark', 'victor53@gmail.com', 'Dr34mC4tch3r', 0),
       ('Wendy', 'Rodriguez', 'wendy22@gmail.com', 'L1ghtBr33z3', 0),
       ('Xavier', 'Lewis', 'xavier41@gmail.com', 'Sh@dowM00n', 0),
       ('Yvonne', 'Walker', 'yvonne30@gmail.com', 'R1s1ngSun', 0),
       ('Zane', 'Hall', 'zane49@gmail.com', 'DuskT1llD4wn', 0);

INSERT INTO user_details (address, address2, city, state, zip, phone, img_file_path, user_id)
VALUES
    ('1234 Trout Rd', 'Apt 205', 'Dallas', 'TX', '75201', '2145551212', '/img/users/user1.jpg', 1),
    ('5678 Bass Ave', NULL, 'Dallas', 'TX', '75202', '2145551313', '/img/users/user2.jpg', 2),
    ('9101 Salmon Ln', NULL, 'Dallas', 'TX', '75203', '2145551414', '/img/users/user3.jpg', 3),
    ('2468 Tuna Dr', 'Suite 101', 'Dallas', 'TX', '75204', '2145551515', '/img/users/user4.jpg', 4),
    ('1357 Sardine St', NULL, 'Dallas', 'TX', '75205', '2145551616', '/img/users/user5.jpg', 5),
    ('3690 Mackerel Rd', NULL, 'Dallas', 'TX', '75206', '2145551717', '/img/users/user6.jpg', 6),
    ('8025 Halibut Ave', NULL, 'Dallas', 'TX', '75207', '2145551818', '/img/users/user7.jpg', 7),
    ('4747 Grouper Ln', 'Apt 301', 'Dallas', 'TX', '75208', '2145551919', '/img/users/user8.jpg', 8),
    ('6363 Catfish St', NULL, 'Dallas', 'TX', '75209', '2145552020', '/img/users/user9.jpg', 9),
    ('9821 Flounder Rd', NULL, 'Dallas', 'TX', '75210', '2145552121', '/img/users/user10.jpg', 10),
    ('7407 Perch Ave', NULL, 'Dallas', 'TX', '75211', '2145552222', '/img/users/user11.jpg', 11),
    ('5935 Pike Dr', 'Suite 202', 'Dallas', 'TX', '75212', '2145552323', '/img/users/user12.jpg', 12),
    ('2589 Marlin St', NULL, 'Dallas', 'TX', '75213', '2145552424', '/img/users/user13.jpg', 13),
    ('7164 Swordfish Rd', NULL, 'Dallas', 'TX', '75214', '2145552525', '/img/users/user14.jpg', 14),
    ('4982 Haddock Ave', NULL, 'Dallas', 'TX', '75215', '2145552626', '/img/users/user15.jpg', 15),
    ('1746 Eel Ln', 'Apt 401', 'Dallas', 'TX', '75216', '2145552727', '/img/users/user16.jpg', 16),
    ('3210 Shark St', NULL, 'Dallas', 'TX', '75217', '2145552828', '/img/users/user17.jpg', 17),
    ('8653 Carp Rd', NULL, 'Dallas', 'TX', '75218', '2145552929', '/img/users/user18.jpg', 18),
    ('6971 Lobster Ave', NULL, 'Dallas', 'TX', '75219', '2145553030', '/img/users/user19.jpg', 19),
    ('9312 Snapper Dr', NULL, 'Dallas', 'TX', '75220', '2145553131', '/img/users/user20.jpg', 20),
    ('5671 Fluke St', 'Apt 501', 'Dallas', 'TX', '75221', '2145553232', '/img/users/user21.jpg', 21),
    ('8902 Whiting Rd', NULL, 'Dallas', 'TX', '75222', '2145553333', '/img/users/user22.jpg', 22),
    ('4563 Anchovy Ave', NULL, 'Dallas', 'TX', '75223', '2145553434', '/img/users/user23.jpg', 23),
    ('2357 Goby Dr', NULL, 'Dallas', 'TX', '75224', '2145553535', '/img/users/user24.jpg', 24),
    ('6895 Minnow St', 'Suite 301', 'Dallas', 'TX', '75225', '2145553636', '/img/users/user25.jpg', 25),
    ('4189 Pike Rd', NULL, 'Dallas', 'TX', '75226', '2145553737', '/img/users/user26.jpg', 26),
    ('7831 Perch Ave', NULL, 'Dallas', 'TX', '75227', '2145553838', '/img/users/user27.jpg', 27);

INSERT INTO honeydoers (rating, about_self, user_id) VALUES
     (4.5, 'I love helping people with their tasks. I am reliable and hardworking.', 1),
     (4.7, 'I am a taskmaster. No task is too big or small for me.', 2),
     (4.8, 'I enjoy the challenge of completing tasks efficiently and accurately.', 3),
     (4.3, 'I am a doer. I get things done quickly and effectively.', 4),
     (4.6, 'I believe in doing things right the first time. I am meticulous in my work.', 5),
     (4.9, 'I am passionate about helping others and always complete tasks to the best of my ability.', 6),
     (4.2, 'I am a problem solver. I enjoy finding solutions to any challenge.', 7),
     (4.7, 'I am dedicated and thorough. I ensure all tasks are completed to the highest standard.', 8),
     (4.4, 'I am a handyman at heart. I love tackling new tasks and learning new skills.', 9),
     (4.8, 'I am driven by results. I strive to complete all tasks efficiently and effectively.', 10),
     (4.5, 'I am a hard worker and take pride in my work. I strive for excellence in everything I do.', 11),
     (4.3, 'I love helping others and am committed to providing excellent service.', 12),
     (4.6, 'I am experienced in many areas and can handle a variety of tasks.', 13),
     (4.4, 'I am reliable, efficient, and hardworking. I always strive to exceed expectations.', 14),
     (4.9, 'I am highly motivated and enjoy helping others. I always deliver high-quality work.', 15),
     (4.7, 'I am a dedicated worker and take pride in completing tasks accurately and timely.', 16),
     (4.5, 'I am a quick learner and am always looking for new challenges.', 17),
     (4.6, 'I am efficient and reliable. I always aim to provide excellent service.', 18),
     (4.8, 'I am highly skilled and experienced. I enjoy helping others and always deliver high-quality work.', 19),
     (4.7, 'I am detail-oriented and committed to excellence. I always ensure tasks are completed to the highest standard.', 20),
     (4.9, 'I am dedicated, reliable, and always strive to exceed expectations.', 21),
     (4.5, 'I am a skilled worker who loves helping others. I always complete tasks to the best of my ability.', 22),
     (4.8, 'I am a motivated individual who is passionate about providing excellent service.', 23),
     (4.7, 'I am hardworking and committed to providing high-quality work. I love helping others.', 24),
     (4.5, 'I am experienced and efficient. I enjoy taking on new tasks and always complete them to the highest standard.', 25),
     (4.7, 'I am a taskmaster. No task is too big or small for me.', 26),
     (4.6, 'I am experienced in many areas and can handle a variety of tasks.', 27);


INSERT INTO categories (name, description, img_file_path) VALUES
      ('Exterior', 'Lawn mowing and garden maintenance', '/img/categories/exterior.jpg'),
      ('Interior', 'Plumbing and fixture installation', '/img/categories/interior.jpg'),
      ('Miscellaneous', 'Moving heavy furniture and items', '/img/categories/miscellaneous.jpg');
#       ('Exterior', 'Deck and patio cleanup', '/img/categories/exterior2.jpg'),
#       ('Interior', 'Painting walls and ceilings', '/img/categories/interior2.jpg'),
#       ('Miscellaneous', 'Organizing garage or basement', '/img/categories/miscellaneous2.jpg'),
#       ('Exterior', 'Gutter cleaning and maintenance', '/img/categories/exterior3.jpg'),
#       ('Interior', 'Flooring installation and repair', '/img/categories/interior3.jpg'),
#       ('Miscellaneous', 'Cleaning high and hard-to-reach areas', '/img/categories/miscellaneous3.jpg'),
#       ('Exterior', 'Tree trimming and landscaping', '/img/categories/exterior4.jpg'),
#       ('Interior', 'Appliance installation and repair', '/img/categories/interior4.jpg'),
#       ('Miscellaneous', 'Assembling furniture or toys', '/img/categories/miscellaneous4.jpg'),
#       ('Exterior', 'Power washing siding and driveways', '/img/categories/exterior5.jpg'),
#       ('Interior', 'Wallpaper removal and installation', '/img/categories/interior5.jpg'),
#       ('Miscellaneous', 'Hanging pictures and shelving', '/img/categories/miscellaneous5.jpg'),
#       ('Exterior', 'Outdoor furniture assembly', '/img/categories/exterior6.jpg'),
#       ('Interior', 'Cabinetry installation and repair', '/img/categories/interior6.jpg'),
#       ('Miscellaneous', 'General home cleaning', '/img/categories/miscellaneous6.jpg'),
#       ('Exterior', 'Fence and gate repair', '/img/categories/exterior7.jpg'),
#       ('Interior', 'Tile installation and grouting', '/img/categories/interior7.jpg'),
#       ('Miscellaneous', 'Carpet cleaning and stain removal', '/img/categories/miscellaneous7.jpg'),
#       ('Exterior', 'Exterior painting and touch ups', '/img/categories/exterior8.jpg'),
#       ('Interior', 'Window and door installation', '/img/categories/interior8.jpg'),
#       ('Miscellaneous', 'Attic or crawl space cleanouts', '/img/categories/miscellaneous8.jpg');

INSERT INTO services (name, description, img_file_path, category_id) VALUES
     ('Exterior Painting', 'Application of weather-proof paint to exterior surfaces including walls, fences, and garages.', '/img/services/exterior_painting.jpg', 1),
     ('Interior Painting', 'Professional application of paint to interior walls, ceilings, and trim.', '/img/services/interior_painting.jpg', 2),
     ('Installing Electrical Fixtures', 'Installation and replacement of light fixtures, ceiling fans, and other electrical appliances.', '/img/services/electrical_fixtures.jpg', 2),
     ('Installing Plumbing Fixtures', 'Installation, upgrade, and replacement of sinks, toilets, showers, and other plumbing fixtures.', '/img/services/plumbing_fixtures.jpg', 2),
     ('Landscaping', 'Garden design, lawn care, planting, tree trimming, and other landscaping services.', '/img/services/landscaping.jpg', 1),
     ('Moving/Hauling', 'Heavy lifting, furniture relocation, hauling away of debris, trash, and unwanted items.', '/img/services/moving_hauling.jpg', 3),
     ('Assembling Furniture', 'Assembly of furniture items from beds and tables to shelving units and office furniture.', '/img/services/furniture_assembly.jpg', 3),
     ('Mounting TVs', 'Secure mounting of televisions to walls, including cable management for a clean and professional look.', '/img/services/tv_mounting.jpg', 2),
     ('Gutter Cleaning', 'Cleaning and maintenance of gutters to prevent water damage and protect the home’s foundation.', '/img/services/gutter_cleaning.jpg', 1),
     ('Flooring Installation', 'Installation of various types of flooring including hardwood, laminate, and tile.', '/img/services/flooring_installation.jpg', 2),
     ('Deck and Patio Cleanup', 'Power washing and cleaning of decks, patios, and outdoor furniture.', '/img/services/deck_patio_cleanup.jpg', 1),
     ('Cabinetry Installation', 'Installation and repair of kitchen and bathroom cabinets and drawers.', '/img/services/cabinetry_installation.jpg', 2),
     ('Fence and Gate Repair', 'Repair and installation of fences and gates to enhance home security and curb appeal.', '/img/services/fence_gate_repair.jpg', 1),
     ('Wallpaper Installation', 'Professional installation and removal of wallpaper in various room types.', '/img/services/wallpaper_installation.jpg', 2),
     ('Appliance Installation', 'Installation and connection of major household appliances.', '/img/services/appliance_installation.jpg', 2),
     ('General Home Cleaning', 'Comprehensive cleaning services for all areas of the home.', '/img/services/home_cleaning.jpg', 3),
     ('Garage Organization', 'Sorting, organizing, and cleaning services for cluttered garages.', '/img/services/garage_organization.jpg', 3),
     ('Window Installation', 'Installation and replacement of windows to improve home insulation and curb appeal.', '/img/services/window_installation.jpg', 2),
     ('Power Washing', 'Power washing services for driveways, siding, decks, and patios.', '/img/services/power_washing.jpg', 1),
     ('Tile Installation', 'Professional installation of wall and floor tiles in kitchens, bathrooms, and other spaces.', '/img/services/tile_installation.jpg', 2),
     ('Attic Cleanout', 'Cleaning and organization services for cluttered attics.', '/img/services/attic_cleanout.jpg', 2);

INSERT INTO honeydoer_services (rate, about_service, service_id, honeydoer_id) VALUES
            (25.00, 'Experienced exterior painter using high quality, weather-resistant materials.', 1, 1),
            (30.00, 'Specializes in interior painting with clean lines and attention to detail.', 2, 2),
            (35.00, 'Proficient in installing a variety of electrical fixtures with safety in mind.', 3, 3),
            (40.00, 'Experienced plumber who can handle installation of all types of plumbing fixtures.', 4, 4),
            (50.00, 'Landscape expert offering a variety of gardening and outdoor beautification services.', 5, 5),
            (15.00, 'Efficient mover with a strong work ethic, can help with hauling and heavy lifting tasks.', 6, 6),
            (20.00, 'Furniture assembly expert skilled at putting together a wide range of items.', 7, 7),
            (25.00, 'Expert in TV mounting, ensuring secure fixtures and clean cable management.', 8, 8),
            (20.00, 'Experienced in gutter cleaning, maintenance, and repair for optimal home protection.', 9, 9),
            (45.00, 'Professional installer of hardwood, laminate, and tile flooring.', 10, 10),
            (25.00, 'Specializes in outdoor cleaning and maintenance for decks and patios.', 11, 11),
            (35.00, 'Experienced in installing and repairing cabinetry for kitchens and bathrooms.', 12, 12),
            (30.00, 'Fence and gate repair specialist who can enhance your home security.', 13, 13),
            (30.00, 'Experienced in wallpaper removal and installation for a refreshed look.', 14, 14),
            (40.00, 'Experienced in the installation and setup of major household appliances.', 15, 15),
            (20.00, 'Comprehensive home cleaning services with great attention to detail.', 16, 16),
            (20.00, 'Professional garage organizer who can sort, clean, and declutter spaces.', 17, 17),
            (40.00, 'Skilled at installing and replacing windows for improved home efficiency.', 18, 18),
            (30.00, 'Offers power washing services to restore the look of outdoor spaces.', 19, 19),
            (40.00, 'Professional tile installer for kitchens, bathrooms, and other spaces.', 20, 20),
            (20.00, 'Provides efficient attic cleaning and organization services.', 21, 21),
            (30.00, 'Specializes in exterior painting, using long-lasting, weather-resistant materials.', 1, 22),
            (35.00, 'Interior painting with attention to detail and high-quality materials.', 2, 23),
            (30.00, 'Installation of various electrical fixtures with safety and function in mind.', 3, 24),
            (40.00, 'Plumbing expert capable of installing a variety of fixtures.', 4, 25),
            (35.00, 'Installation of various electrical fixtures with safety and function in mind.', 3, 26),
            (35.00, 'Plumbing expert capable of installing a variety of fixtures.', 4, 27);
INSERT INTO tasks (task_details, date_assigned, date_completed, status, is_accepted, user_id, honeydoer_service_id) VALUES
      ('Paint exterior fence', '2023-06-02', NULL, 'Assigned', 1, 1, 1),
      ('Paint living room', '2023-06-02', NULL, 'Assigned', 1, 2, 2),
      ('Install new ceiling fan', '2023-06-02', NULL, 'Assigned', 1, 3, 3),
      ('Replace bathroom sink', '2023-06-02', NULL, 'Assigned', 1, 4, 4),
      ('Landscaping front yard', '2023-06-02', NULL, 'Assigned', 1, 5, 5),
      ('Move furniture to storage', '2023-06-02', NULL, 'Assigned', 1, 6, 6),
      ('Assemble new dining set', '2023-06-02', NULL, 'Assigned', 1, 7, 7),
      ('Mount TV in living room', '2023-06-02', NULL, 'Assigned', 1, 8, 8),
      ('Clean gutters', '2023-06-02', NULL, 'Assigned', 1, 9, 9),
      ('Install laminate flooring in kitchen', '2023-06-02', NULL, 'Assigned', 1, 10, 10),
      ('Power wash deck', '2023-06-02', NULL, 'Assigned', 1, 11, 11),
      ('Install kitchen cabinets', '2023-06-02', '2023-06-02', 'Completed', 1, 12, 12),
      ('Repair backyard fence', '2023-06-02', NULL, 'In Progress', 1, 13, 13),
      ('Remove wallpaper in guest room', '2023-06-02', NULL, 'Assigned', 1, 14, 14),
      ('Install dishwasher', '2023-06-02', NULL, 'In Progress', 1, 15, 15),
      ('Clean entire house', '2023-06-02', NULL, 'Assigned', 1, 16, 16),
      ('Organize garage', '2023-06-02', NULL, 'Assigned', 1, 17, 17),
      ('Replace living room window', '2023-06-02', '2023-06-02', 'Completed', 1, 18, 18),
      ('Power wash driveway', '2023-06-02', NULL, 'Assigned', 1, 19, 19),
      ('Install tile in bathroom', '2023-06-02', NULL, 'Assigned', 1, 20, 20),
      ('Clean out attic', '2023-06-02', NULL, 'In Progress', 1, 21, 21);
INSERT INTO task_costs (honeydoer_pay, site_pay, total_user_cost, taxes, task_id) VALUES
           (80, 16, 102.6, 6.6, 1),
           (150, 30, 193.875, 13.875, 2),
           (100, 20, 128.5, 8.5, 3),
           (120, 24, 154.2, 10.2, 4),
           (180, 36, 231.45, 15.45, 5),
           (70, 14, 90.775, 6.775, 6),
           (50, 10, 65.375, 5.375, 7),
           (100, 20, 128.5, 8.5, 8),
           (60, 12, 77.7, 5.7, 9),
           (200, 40, 257, 17, 10),
           (75, 15, 96.5625, 6.5625, 11),
           (150, 30, 193.875, 13.875, 12),
           (100, 20, 128.5, 8.5, 13),
           (80, 16, 102.6, 6.6, 14),
           (180, 36, 231.45, 15.45, 15),
           (70, 14, 90.775, 6.775, 16),
           (60, 12, 77.7, 5.7, 17),
           (160, 32, 205.2, 13.2, 18),
           (90, 18, 115.425, 7.425, 19),
           (200, 40, 257, 17, 20),
           (75, 15, 96.5625, 6.5625, 21);
INSERT INTO honeydoer_reviews (stars, comment, task_id, honeydoer_id) VALUES
      ('FIVE', 'Excellent work on painting the fence. Highly recommended.', 1, 1),
      ('FOUR', 'Very good job on painting the living room, but a bit slow.', 2, 2),
      ('THREE', 'Installation of the ceiling fan was okay, but not great.', 3, 3),
      ('FOUR', 'Good work on replacing the bathroom sink.', 4, 4),
      ('FIVE', 'Fantastic landscaping job in the front yard!', 5, 5),
      ('FOUR', 'Good job on moving the furniture, but arrived late.', 6, 6),
      ('FIVE', 'Did an excellent job assembling the new dining set.', 7, 7),
      ('FOUR', 'Good work on mounting the TV, but missed a step in the manual.', 8, 8),
      ('FIVE', 'Did a great job cleaning the gutters.', 9, 9),
      ('THREE', 'Flooring installation was average, not as good as expected.', 10, 10),
      ('FOUR', 'Deck looks much better after the power wash.', 11, 11),
      ('FIVE', 'Installed the kitchen cabinets perfectly!', 12, 12),
      ('FOUR', 'Fence repair was good, but left a small mess in the yard.', 13, 13),
      ('FOUR', 'Removal of wallpaper was done well, but took longer than estimated.', 14, 14),
      ('FIVE', 'Installed the dishwasher quickly and efficiently.', 15, 15),
      ('THREE', 'House cleaning was average, missed some areas.', 16, 16),
      ('FIVE', 'Organized the garage beautifully! Very pleased with the result.', 17, 17),
      ('FOUR', 'Did a good job replacing the window.', 18, 18),
      ('FOUR', 'Driveway looks cleaner after the power wash.', 19, 19),
      ('FIVE', 'Excellent tile installation in the bathroom.', 20, 20),
      ('FIVE', 'Efficient and thorough cleaning of the attic.', 21, 21);
INSERT INTO client_reviews (stars, comment, task_id, user_id) VALUES
      ('FIVE', 'Very responsible and respectful client.', 1, 1),
      ('FOUR', 'Good client but needed more clarity in task description.', 2, 2),
      ('THREE', 'Client was difficult to work with.', 3, 3),
      ('FOUR', 'Overall a pleasant experience working with this client.', 4, 4),
      ('FIVE', 'Excellent client! Clear instructions and prompt payment.', 5, 5),
      ('FOUR', 'Good client but there were delays in communication.', 6, 6),
      ('FIVE', 'Amazing client! Would love to work again with them.', 7, 7),
      ('FOUR', 'Client was good but there were some issues with payment.', 8, 8),
      ('FIVE', 'Client was understanding and easy to work with.', 9, 9),
      ('THREE', 'Had difficulties understanding client’s expectations.', 10, 10),
      ('FOUR', 'Good client, but there were issues with task scheduling.', 11, 11),
      ('FIVE', 'Great client! Clear instructions and easy communication.', 12, 12),
      ('FOUR', 'Client was good, but there were some last minute changes.', 13, 13),
      ('FOUR', 'Client was good but had unrealistic expectations.', 14, 14),
      ('FIVE', 'Excellent client! Very professional and understanding.', 15, 15),
      ('THREE', 'Client was difficult to communicate with.', 16, 16),
      ('FIVE', 'Great client! Always available for clarifications.', 17, 17),
      ('FOUR', 'Good client but needs to work on their communication.', 18, 18),
      ('FOUR', 'Client was good but had some issues with payment.', 19, 19),
      ('FIVE', 'Excellent client! Very clear and concise instructions.', 20, 20),
      ('FIVE', 'Amazing client! Would love to work again with them.', 21, 21);
