USE honeydo_helper_db;
INSERT INTO users (first_name, last_name, email, password, is_admin, is_honeydoer)
VALUES ('John', 'Smith', 'john.smith@example.com', 'pAsSw0rD', 0, 1),
       ('Jane', 'Doe', 'jane.doe@example.com', 'Qwerty12', 0, 1),
       ('Michael', 'Johnson', 'michael.johnson@example.com', 'P@ssw0rd', 0, 1),
       ('Emily', 'Davis', 'emily.davis@example.com', 'Rando123', 0, 1),
       ('David', 'Rodriguez', 'david.rodriguez@example.com', 'Password1', 0, 1),
       ('Sarah', 'Wilson', 'sarah.wilson@example.com', 'p@55W0rd', 0, 1),
       ('Matthew', 'Taylor', 'matthew.taylor@example.com', 'Secret12', 0, 1),
       ('Olivia', 'Anderson', 'olivia.anderson@example.com', 'Pass1234', 0, 1),
       ('Christopher', 'Thomas', 'christopher.thomas@example.com', 'p@55word', 0, 1),
       ('Ava', 'Martinez', 'ava.martinez@example.com', 'Password12', 0, 1),
       ('Daniel', 'Hernandez', 'daniel.hernandez@example.com', 's3cret12', 0, 1),
       ('Sophia', 'Lopez', 'sophia.lopez@example.com', 'Secure12', 0, 1),
       ('Andrew', 'Gonzalez', 'andrew.gonzalez@example.com', 'p@ssW0rd', 0, 1),
       ('Isabella', 'Wilson', 'isabella.wilson@example.com', 'pa$$word', 0, 1),
       ('William', 'Lee', 'william.lee@example.com', 'Passw0rd!', 0, 1),
       ('Mia', 'Walker', 'mia.walker@example.com', '12qwerty', 0, 1),
       ('Joseph', 'Hall', 'joseph.hall@example.com', 'p@ssw0rd1', 0, 1),
       ('Charlotte', 'Young', 'charlotte.young@example.com', 'Pass12word', 0, 1),
       ('David', 'Clark', 'david.clark@example.com', 'Password123', 0, 1),
       ('Madison', 'Lewis', 'madison.lewis@example.com', 'pA55word', 0, 1),
       ('Emma', 'Smith', 'emma.smith@example.com', 'pAsSw0rD', 0, 1),
       ('Liam', 'Johnson', 'liam.johnson@example.com', 'Qwerty12', 0, 1),
       ('Olivia', 'Brown', 'olivia.brown@example.com', 'P@ssw0rd', 0, 1),
       ('Noah', 'Taylor', 'noah.taylor@example.com', 'Rando123', 0, 1),
       ('Ava', 'Davis', 'ava.davis@example.com', 'Password1', 0, 1),
       ('Sophia', 'Wilson', 'sophia.wilson@example.com', 'p@55W0rd', 0, 1),
       ('Isabella', 'Thomas', 'isabella.thomas@example.com', 'Secret12', 0, 1),
       ('Mia', 'Martinez', 'mia.martinez@example.com', 'Pass1234', 0, 1),
       ('Charlotte', 'Hernandez', 'charlotte.hernandez@example.com', 'p@55word', 0, 1),
       ('Amelia', 'Lopez', 'amelia.lopez@example.com', 'Password12', 0, 1),
       ('Harper', 'Gonzalez', 'harper.gonzalez@example.com', 's3cret12', 0, 0),
       ('Evelyn', 'Anderson', 'evelyn.anderson@example.com', 'Secure12', 0, 0),
       ('Abigail', 'Clark', 'abigail.clark@example.com', 'p@ssW0rd', 0, 0),
       ('Emily', 'Lewis', 'emily.lewis@example.com', 'pa$$word', 0, 0),
       ('Elizabeth', 'Walker', 'elizabeth.walker@example.com', 'Passw0rd!', 0, 0),
       ('Sofia', 'Hall', 'sofia.hall@example.com', '12qwerty', 0, 0),
       ('Victoria', 'Young', 'victoria.young@example.com', 'p@ssw0rd1', 0, 0),
       ('Madison', 'Lee', 'madison.lee@example.com', 'Pass12word', 0, 0),
       ('Scarlett', 'White', 'scarlett.white@example.com', 'Password123', 0, 0),
       ('Grace', 'Harris', 'grace.harris@example.com', 'pA55word', 0, 0),
       ('Ethan', 'Martin', 'ethan.martin@example.com', 'pAsSw0rD', 0, 0),
       ('Luna', 'Thompson', 'luna.thompson@example.com', 'Qwerty12', 0, 0),
       ('Henry', 'Wright', 'henry.wright@example.com', 'P@ssw0rd', 0, 0),
       ('Chloe', 'Harris', 'chloe.harris@example.com', 'Rando123', 0, 0),
       ('Sebastian', 'Mitchell', 'sebastian.mitchell@example.com', 'Password1', 0, 0),
       ('Lily', 'King', 'lily.king@example.com', 'p@55W0rd', 0, 0),
       ('Jackson', 'Scott', 'jackson.scott@example.com', 'Secret12', 0, 0),
       ('Zoe', 'Baker', 'zoe.baker@example.com', 'Pass1234', 0, 0),
       ('Lucas', 'Garcia', 'lucas.garcia@example.com', 'p@55word', 0, 0),
       ('Nora', 'Wood', 'nora.wood@example.com', 'Password12', 0, 0),
       ('Elijah', 'Morris', 'elijah.morris@example.com', 's3cret12', 0, 0),
       ('Avery', 'Anderson', 'avery.anderson@example.com', 'Secure12', 0, 0),
       ('Mila', 'White', 'mila.white@example.com', 'p@ssW0rd', 0, 0),
       ('Benjamin', 'Robinson', 'benjamin.robinson@example.com', 'pa$$word', 0, 0),
       ('Hannah', 'Ward', 'hannah.ward@example.com', 'Passw0rd!', 0, 0),
       ('Alexander', 'Perez', 'alexander.perez@example.com', '12qwerty', 0, 0),
       ('Grace', 'Turner', 'grace.turner@example.com', 'p@ssw0rd1', 0, 0),
       ('Leo', 'Collins', 'leo.collins@example.com', 'Pass12word', 0, 0),
       ('Samantha', 'Cook', 'samantha.cook@example.com', 'Password123', 0, 0),
       ('Liam', 'Barnes', 'liam.barnes@example.com', 'pA55word', 0, 0),
       ('Aiden', 'Phillips', 'aiden.phillips@example.com', 'pAsSw0rD', 0, 0),
       ('Scarlett', 'Morris', 'scarlett.morris@example.com', 'Qwerty12', 0, 0),
       ('Carter', 'Cooper', 'carter.cooper@example.com', 'P@ssw0rd', 0, 0),
       ('Ella', 'Rivera', 'ella.rivera@example.com', 'Rando123', 0, 0),
       ('Gabriel', 'Peterson', 'gabriel.peterson@example.com', 'Password1', 0, 0),
       ('Stella', 'Morgan', 'stella.morgan@example.com', 'p@55W0rd', 0, 0),
       ('Ryan', 'Reed', 'ryan.reed@example.com', 'Secret12', 0, 0),
       ('Natalie', 'Bell', 'natalie.bell@example.com', 'Pass1234', 0, 0),
       ('Julian', 'Parker', 'julian.parker@example.com', 'p@55word', 0, 0),
       ('Penelope', 'Gonzalez', 'penelope.gonzalez@example.com', 'Password12', 0, 0),
       ('Leo', 'Wright', 'leo.wright@example.com', 's3cret12', 0, 0),
       ('Brooklyn', 'Hughes', 'brooklyn.hughes@example.com', 'Secure12', 0, 0),
       ('Lucy', 'Baker', 'lucy.baker@example.com', 'p@ssW0rd', 0, 0),
       ('Zachary', 'Roberts', 'zachary.roberts@example.com', 'pa$$word', 0, 0),
       ('Landon', 'Sanders', 'landon.sanders@example.com', 'Passw0rd!', 0, 0),
       ('Aria', 'Price', 'aria.price@example.com', '12qwerty', 0, 0),
       ('Grayson', 'Ramirez', 'grayson.ramirez@example.com', 'p@ssw0rd1', 0, 0),
       ('Riley', 'Watson', 'riley.watson@example.com', 'Pass12word', 0, 0),
       ('Levi', 'Foster', 'levi.foster@example.com', 'Password123', 0, 0),
       ('Victoria', 'Barnes', 'victoria.barnes@example.com', 'pA55word', 0, 0);


INSERT INTO user_profile (address, address2, city, state, zip, phone, img_file_path, user_id)
VALUES ('1234 Trout Rd', 'Apt 205', 'Dallas', 'TX', '75201', '2145551212', '/img/users/user1.jpg', 1),
       ('5678 Bass Ave', NULL, 'Dallas', 'TX', '75202', '2145551313', '/img/users/user2.jpg', 2),
       ('9101 Salmon Ln', NULL, 'Dallas', 'TX', '75203', '2145551414', '/img/users/user3.jpg', 3),
       ('2468 Tuna Dr', 'Suite 101', 'Dallas', 'TX', '75204', '2145551515', '/img/users/user4.jpg', 4),
       ('1357 Sardine St', NULL, 'Dallas', 'TX', '75205', '2145551616', '/img/users/user5.jpg', 5),
       ('3690 Mackerel Rd', NULL, 'Dallas', 'TX', '75206', '2145551717', '/img/users/user6.jpg', 6),
       ('8025 Halibut Ave', NULL, 'Dallas', 'TX', '75207', '2145551818', '/img/users/user7.jpg', 7),
       ('4747 Grouper Ln', 'Apt 301', 'Dallas', 'TX', '75208', '2145551919', '/img/users/user8.jpg', 8),
       ('6363 Catfish St', NULL, 'Dallas', 'TX', '75209', '2145552020', '/img/users/user9.jpg', 9),
       ('9821 Flounder Rd', NULL, 'Dallas', 'TX', '75210', '2145552121', '/img/users/user10.jpg', 10),
       ('7407 Perch Ave', NULL, 'Dallas', 'TX', '75211', '2145552222', '/img/users/user11.jpg', 11),
       ('5935 Pike Dr', 'Suite 202', 'Dallas', 'TX', '75212', '2145552323', '/img/users/user12.jpg', 12),
       ('2589 Marlin St', NULL, 'Dallas', 'TX', '75213', '2145552424', '/img/users/user13.jpg', 13),
       ('7164 Swordfish Rd', NULL, 'Dallas', 'TX', '75214', '2145552525', '/img/users/user14.jpg', 14),
       ('4982 Haddock Ave', NULL, 'Dallas', 'TX', '75215', '2145552626', '/img/users/user15.jpg', 15),
       ('1746 Eel Ln', 'Apt 401', 'Dallas', 'TX', '75216', '2145552727', '/img/users/user16.jpg', 16),
       ('3210 Shark St', NULL, 'Dallas', 'TX', '75217', '2145552828', '/img/users/user17.jpg', 17),
       ('8653 Carp Rd', NULL, 'Dallas', 'TX', '75218', '2145552929', '/img/users/user18.jpg', 18),
       ('6971 Lobster Ave', NULL, 'Dallas', 'TX', '75219', '2145553030', '/img/users/user19.jpg', 19),
       ('9312 Snapper Dr', NULL, 'Dallas', 'TX', '75220', '2145553131', '/img/users/user20.jpg', 20),
       ('1023 Mahi Mahi Rd', 'Apt 101', 'Dallas', 'TX', '75221', '2145553232', '/img/users/user21.jpg', 21),
       ('6489 Marlin St', NULL, 'Dallas', 'TX', '75222', '2145553333', '/img/users/user22.jpg', 22),
       ('4512 Swordfish Rd', NULL, 'Dallas', 'TX', '75223', '2145553434', '/img/users/user23.jpg', 23),
       ('8734 Halibut Ave', NULL, 'Dallas', 'TX', '75224', '2145553535', '/img/users/user24.jpg', 24),
       ('2156 Snapper Dr', 'Suite 301', 'Dallas', 'TX', '75225', '2145553636', '/img/users/user25.jpg', 25),
       ('7491 Haddock Ave', NULL, 'Dallas', 'TX', '75226', '2145553737', '/img/users/user26.jpg', 26),
       ('5087 Carp Rd', NULL, 'Dallas', 'TX', '75227', '2145553838', '/img/users/user27.jpg', 27),
       ('9963 Perch Ave', NULL, 'Dallas', 'TX', '75228', '2145553939', '/img/users/user28.jpg', 28),
       ('3628 Tuna Dr', 'Apt 501', 'Dallas', 'TX', '75229', '2145554040', '/img/users/user29.jpg', 29),
       ('1047 Lobster Ave', NULL, 'Dallas', 'TX', '75230', '2145554141', '/img/users/user30.jpg', 30),
       ('5904 Bass Ave', NULL, 'Dallas', 'TX', '75231', '2145554242', '/img/users/user31.jpg', 31),
       ('2379 Grouper Ln', NULL, 'Dallas', 'TX', '75232', '2145554343', '/img/users/user32.jpg', 32),
       ('7815 Flounder Rd', 'Suite 401', 'Dallas', 'TX', '75233', '2145554444', '/img/users/user33.jpg', 33),
       ('4261 Catfish St', NULL, 'Dallas', 'TX', '75234', '2145554545', '/img/users/user34.jpg', 34),
       ('9680 Sardine St', NULL, 'Dallas', 'TX', '75235', '2145554646', '/img/users/user35.jpg', 35),
       ('6046 Mackerel Rd', NULL, 'Dallas', 'TX', '75236', '2145554747', '/img/users/user36.jpg', 36),
       ('3621 Pike Dr', 'Apt 601', 'Dallas', 'TX', '75237', '2145554848', '/img/users/user37.jpg', 37),
       ('1089 Salmon Ln', NULL, 'Dallas', 'TX', '75238', '2145554949', '/img/users/user38.jpg', 38),
       ('5463 Eel Ln', NULL, 'Dallas', 'TX', '75239', '2145555050', '/img/users/user39.jpg', 39),
       ('1897 Shark St', NULL, 'Dallas', 'TX', '75240', '2145555151', '/img/users/user40.jpg', 40),
       ('3821 Mahi Mahi Rd', NULL, 'Dallas', 'TX', '75241', '2145555252', '/img/users/user41.jpg', 41),
       ('8275 Marlin St', 'Suite 201', 'Dallas', 'TX', '75242', '2145555353', '/img/users/user42.jpg', 42),
       ('5692 Swordfish Rd', NULL, 'Dallas', 'TX', '75243', '2145555454', '/img/users/user43.jpg', 43),
       ('2148 Halibut Ave', NULL, 'Dallas', 'TX', '75244', '2145555555', '/img/users/user44.jpg', 44),
       ('7463 Snapper Dr', NULL, 'Dallas', 'TX', '75245', '2145555656', '/img/users/user45.jpg', 45),
       ('4919 Haddock Ave', 'Apt 301', 'Dallas', 'TX', '75246', '2145555757', '/img/users/user46.jpg', 46),
       ('9635 Carp Rd', NULL, 'Dallas', 'TX', '75247', '2145555858', '/img/users/user47.jpg', 47),
       ('6051 Perch Ave', NULL, 'Dallas', 'TX', '75248', '2145555959', '/img/users/user48.jpg', 48),
       ('3594 Tuna Dr', NULL, 'Dallas', 'TX', '75249', '2145556060', '/img/users/user49.jpg', 49),
       ('1027 Lobster Ave', 'Suite 401', 'Dallas', 'TX', '75250', '2145556161', '/img/users/user50.jpg', 50),
       ('6483 Bass Ave', NULL, 'Dallas', 'TX', '75251', '2145556262', '/img/users/user51.jpg', 51),
       ('4518 Grouper Ln', NULL, 'Dallas', 'TX', '75252', '2145556363', '/img/users/user52.jpg', 52),
       ('8754 Flounder Rd', NULL, 'Dallas', 'TX', '75253', '2145556464', '/img/users/user53.jpg', 53),
       ('2179 Catfish St', 'Apt 501', 'Dallas', 'TX', '75254', '2145556565', '/img/users/user54.jpg', 54),
       ('7412 Sardine St', NULL, 'Dallas', 'TX', '75255', '2145556666', '/img/users/user55.jpg', 55),
       ('5068 Mackerel Rd', NULL, 'Dallas', 'TX', '75256', '2145556767', '/img/users/user56.jpg', 56),
       ('9663 Pike Dr', NULL, 'Dallas', 'TX', '75257', '2145556868', '/img/users/user57.jpg', 57),
       ('3610 Salmon Ln', 'Suite 601', 'Dallas', 'TX', '75258', '2145556969', '/img/users/user58.jpg', 58),
       ('1057 Eel Ln', NULL, 'Dallas', 'TX', '75259', '2145557070', '/img/users/user59.jpg', 59),
       ('5942 Shark St', NULL, 'Dallas', 'TX', '75260', '2145557171', '/img/users/user60.jpg', 60),
       ('3821 Herring Rd', NULL, 'Dallas', 'TX', '75261', '2145557272', '/img/users/user61.jpg', 61),
       ('8275 Sablefish St', 'Suite 201', 'Dallas', 'TX', '75262', '2145557373', '/img/users/user62.jpg', 62),
       ('5692 Gurnard Rd', NULL, 'Dallas', 'TX', '75263', '2145557474', '/img/users/user63.jpg', 63),
       ('2148 Sturgeon Ave', NULL, 'Dallas', 'TX', '75264', '2145557575', '/img/users/user64.jpg', 64),
       ('7463 Mahi Mahi Dr', NULL, 'Dallas', 'TX', '75265', '2145557676', '/img/users/user65.jpg', 65),
       ('4919 Mullet St', 'Apt 301', 'Dallas', 'TX', '75266', '2145557777', '/img/users/user66.jpg', 66),
       ('9635 John Dory Rd', NULL, 'Dallas', 'TX', '75267', '2145557878', '/img/users/user67.jpg', 67),
       ('6051 Barracuda Ave', NULL, 'Dallas', 'TX', '75268', '2145557979', '/img/users/user68.jpg', 68),
       ('3594 Grouper Ln', NULL, 'Dallas', 'TX', '75269', '2145558080', '/img/users/user69.jpg', 69),
       ('1027 Salmon Rd', 'Suite 401', 'Dallas', 'TX', '75270', '2145558181', '/img/users/user70.jpg', 70),
       ('6483 Swordfish Ave', NULL, 'Dallas', 'TX', '75271', '2145558282', '/img/users/user71.jpg', 71),
       ('4518 Trout Ln', NULL, 'Dallas', 'TX', '75272', '2145558383', '/img/users/user72.jpg', 72),
       ('8754 Tilapia Rd', NULL, 'Dallas', 'TX', '75273', '2145558484', '/img/users/user73.jpg', 73),
       ('2179 Flounder St', 'Apt 501', 'Dallas', 'TX', '75274', '2145558585', '/img/users/user74.jpg', 74),
       ('7412 Cod Dr', NULL, 'Dallas', 'TX', '75275', '2145558686', '/img/users/user75.jpg', 75),
       ('5068 Sole Rd', NULL, 'Dallas', 'TX', '75276', '2145558787', '/img/users/user76.jpg', 76),
       ('9663 Catfish Ave', NULL, 'Dallas', 'TX', '75277', '2145558888', '/img/users/user77.jpg', 77),
       ('3610 Sardine Ln', 'Suite 601', 'Dallas', 'TX', '75278', '2145558989', '/img/users/user78.jpg', 78),
       ('1057 Haddock Dr', NULL, 'Dallas', 'TX', '75279', '2145559090', '/img/users/user79.jpg', 79),
       ('5942 Mackerel St', NULL, 'Dallas', 'TX', '75280', '2145559191', '/img/users/user80.jpg', 80);


INSERT INTO honeydoers (rating, about_self, user_id)
VALUES (ROUND(RAND() * 3 + 2, 1), 'Experienced contractor with a strong work ethic and a dedication to customer satisfaction. I have been providing quality services for many years and have a proven track record of completing projects on time and within budget.', 1),
       (ROUND(RAND() * 3 + 2, 1), 'Reliable and efficient contractor with a keen attention to detail. I take pride in delivering high-quality workmanship and ensuring customer satisfaction. Hire me for all your contracting needs!', 2),
       (ROUND(RAND() * 3 + 2, 1), 'Highly skilled contractor with extensive experience in the industry. I am committed to delivering exceptional results and exceeding customer expectations. Trust me to handle your contracting projects with professionalism and expertise.', 3),
       (ROUND(RAND() * 3 + 2, 1), 'Dedicated and knowledgeable contractor with a strong focus on quality and craftsmanship. I have a deep understanding of the construction industry and can tackle projects of any size. Choose me for reliable and efficient contracting services.', 4),
       (ROUND(RAND() * 3 + 2, 1), 'Experienced contractor specializing in home improvement and renovation projects. I have a passion for transforming spaces and creating beautiful, functional environments. Let me bring your vision to life!', 5),
       (ROUND(RAND() * 3 + 2, 1), 'Experienced contractor specializing in home renovations and remodeling projects. I have a strong eye for design and can bring your ideas to life. Hire me for top-quality craftsmanship and attention to detail.', 6),
       (ROUND(RAND() * 3 + 2, 1), 'Reliable and efficient contractor with expertise in plumbing and electrical work. I am skilled in handling various installation and repair projects. Choose me for professional service and excellent results.', 7),
       (ROUND(RAND() * 3 + 2, 1), 'Experienced carpenter with a passion for woodworking. I can create custom pieces and provide solutions for all your carpentry needs. Trust me to deliver exceptional craftsmanship and customer satisfaction.', 8),
       (ROUND(RAND() * 3 + 2, 1), 'Skilled contractor specializing in kitchen and bathroom remodeling. I can transform your spaces with modern designs and high-quality materials. Let me create the perfect environment for you.', 9),
       (ROUND(RAND() * 3 + 2, 1), 'Expert contractor with a focus on energy-efficient solutions. I specialize in insulation, window installation, and HVAC systems. Choose me to enhance your home''s comfort and energy savings.', 10),
       (ROUND(RAND() * 3 + 2, 1), 'Experienced landscaper offering a wide range of gardening and outdoor beautification services. I can transform your yard into a beautiful oasis.', 11),
       (ROUND(RAND() * 3 + 2, 1), 'Efficient and reliable contractor specializing in home organization and decluttering. Let me create functional and tidy spaces in your home.', 12),
       (ROUND(RAND() * 3 + 2, 1), 'Skilled painter with attention to detail and a focus on delivering high-quality finishes. I can give your home a fresh new look.', 13),
       (ROUND(RAND() * 3 + 2, 1), 'Experienced electrician capable of handling various electrical installation and repair projects. Choose me for safe and reliable electrical work.', 14),
       (ROUND(RAND() * 3 + 2, 1), 'Proficient handyman offering a wide range of general home repair and maintenance services. Let me take care of your to-do list.', 15),
       (ROUND(RAND() * 3 + 2, 1), 'Experienced flooring contractor specializing in the installation and repair of hardwood, laminate, and tile floors.', 16),
       (ROUND(RAND() * 3 + 2, 1), 'Skilled carpenter with expertise in custom woodworking projects. I can bring your vision to life.', 17),
       (ROUND(RAND() * 3 + 2, 1), 'Reliable fence installer with a focus on security and aesthetics. Choose me for durable and stylish fences and gates.', 18),
       (ROUND(RAND() * 3 + 2, 1), 'Experienced wallpaper specialist providing professional wallpaper removal and installation services.', 19),
       (ROUND(RAND() * 3 + 2, 1), 'Proficient HVAC technician offering installation, maintenance, and repair services for heating and cooling systems.', 20),
       (ROUND(RAND() * 3 + 2, 1), 'Experienced plumber offering a wide range of plumbing installation and repair services. Choose me for reliable and efficient plumbing solutions.', 21),
       (ROUND(RAND() * 3 + 2, 1), 'Skilled HVAC technician providing heating and cooling system installation, repair, and maintenance services.', 22),
       (ROUND(RAND() * 3 + 2, 1), 'Proficient in kitchen and bathroom remodeling projects, delivering quality craftsmanship and attention to detail.', 23),
       (ROUND(RAND() * 3 + 2, 1), 'Experienced carpenter specializing in custom woodworking and cabinetry. Let me enhance the aesthetics of your space.', 24),
       (ROUND(RAND() * 3 + 2, 1), 'Reliable general contractor offering a wide range of construction and renovation services. Choose me for your next project.', 25),
       (ROUND(RAND() * 3 + 2, 1), 'Experienced roofer providing roof installation, repair, and maintenance services. Choose me for durable and weather-resistant roofs.', 26),
       (ROUND(RAND() * 3 + 2, 1), 'Skilled flooring contractor offering installation and repair services for various types of flooring materials.', 27),
       (ROUND(RAND() * 3 + 2, 1), 'Proficient in drywall installation, repair, and finishing. Choose me for smooth and seamless walls.', 28),
       (ROUND(RAND() * 3 + 2, 1), 'Experienced landscaper offering landscape design, installation, and maintenance services. Transform your outdoor space with me.', 29),
       (ROUND(RAND() * 3 + 2, 1), 'Reliable painter specializing in interior and exterior painting. Let me refresh the look of your home.', 30);


INSERT INTO categories (name, description, img_file_path)
VALUES ('Exterior', 'Lawn mowing and garden maintenance', '/img/categories/exterior.png'),
       ('Interior', 'Plumbing and fixture installation', '/img/categories/interior.png'),
       ('Miscellaneous', 'Moving heavy furniture and items', '/img/categories/miscellaneous.png');


INSERT INTO services (name, description, img_file_path, category_id)
VALUES ('Exterior Painting',
        'Application of weather-proof paint to exterior surfaces including walls, fences, and garages.',
        '/img/services/exterior_painting.png', 1),
       ('Interior Painting', 'Professional application of paint to interior walls, ceilings, and trim.',
        '/img/services/interior_painting.png', 2),
       ('Installing Electrical Fixtures',
        'Installation and replacement of light fixtures, ceiling fans, and other electrical appliances.',
        '/img/services/electrical_fixtures.png', 2),
       ('Installing Plumbing Fixtures',
        'Installation, upgrade, and replacement of sinks, toilets, showers, and other plumbing fixtures.',
        '/img/services/plumbing_fixtures.png', 2),
       ('Landscaping', 'Garden design, lawn care, planting, tree trimming, and other landscaping services.',
        '/img/services/landscaping.png', 1),
       ('Moving/Hauling', 'Heavy lifting, furniture relocation, hauling away of debris, trash, and unwanted items.',
        '/img/services/moving_hauling.png', 3),
       ('Assembling Furniture',
        'Assembly of furniture items from beds and tables to shelving units and office furniture.',
        '/img/services/furniture_assembly.png', 3),
       ('Mounting TVs',
        'Secure mounting of televisions to walls, including cable management for a clean and professional look.',
        '/img/services/tv_mounting.png', 2),
       ('Gutter Cleaning',
        'Cleaning and maintenance of gutters to prevent water damage and protect the home’s foundation.',
        '/img/services/gutter_cleaning.png', 1),
       ('Flooring Installation', 'Installation of various types of flooring including hardwood, laminate, and tile.',
        '/img/services/flooring_installation.png', 2),
       ('Deck and Patio Cleanup', 'Power washing and cleaning of decks, patios, and outdoor furniture.',
        '/img/services/deck_patio_cleanup.png', 1),
       ('Cabinetry Installation', 'Installation and repair of kitchen and bathroom cabinets and drawers.',
        '/img/services/cabinetry_installation.png', 2),
       ('Fence and Gate Repair',
        'Repair and installation of fences and gates to enhance home security and curb appeal.',
        '/img/services/fence_gate_repair.png', 1),
       ('Wallpaper Installation', 'Professional installation and removal of wallpaper in various room types.',
        '/img/services/wallpaper_installation.png', 2),
       ('Appliance Installation', 'Installation and connection of major household appliances.',
        '/img/services/appliance_installation.png', 2),
       ('General Home Cleaning', 'Comprehensive cleaning services for all areas of the home.',
        '/img/services/home_cleaning.png', 3),
       ('Garage Organization', 'Sorting, organizing, and cleaning services for cluttered garages.',
        '/img/services/garage_organization.png', 3),
       ('Window Installation', 'Installation and replacement of windows to improve home insulation and curb appeal.',
        '/img/services/window_installation.png', 2),
       ('Power Washing', 'Power washing services for driveways, siding, decks, and patios.',
        '/img/services/power_washing.png', 1),
       ('Tile Installation',
        'Professional installation of wall and floor tiles in kitchens, bathrooms, and other spaces.',
        '/img/services/tile_installation.png', 2),
       ('Attic Cleanout', 'Cleaning and organization services for cluttered attics.',
        '/img/services/attic_cleanout.png', 2);


INSERT INTO honeydoer_services (rate, about_service, service_id, honeydoer_id)
VALUES (ROUND(RAND() * 50 + 25, 2), 'Experienced exterior painter using high-quality, weather-resistant materials.', 1, 1),
       (ROUND(RAND() * 50 + 25, 2), 'Specializes in interior painting with clean lines and attention to detail.', 2, 2),
       (ROUND(RAND() * 50 + 25, 2), 'Proficient in installing a variety of electrical fixtures with safety in mind.', 3, 3),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced plumber who can handle the installation of all types of plumbing fixtures.', 4, 4),
       (ROUND(RAND() * 50 + 25, 2), 'Landscape expert offering a variety of gardening and outdoor beautification services.', 5, 5),
       (ROUND(RAND() * 50 + 25, 2), 'Efficient mover with a strong work ethic, can help with hauling and heavy lifting tasks.', 6, 1),
       (ROUND(RAND() * 50 + 25, 2), 'Furniture assembly expert skilled at putting together a wide range of items.', 7, 2),
       (ROUND(RAND() * 50 + 25, 2), 'Expert in TV mounting, ensuring secure fixtures and clean cable management.', 8, 3),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in gutter cleaning, maintenance, and repair for optimal home protection.', 9, 4),
       (ROUND(RAND() * 50 + 25, 2), 'Professional installer of hardwood, laminate, and tile flooring.', 10, 5),
       (ROUND(RAND() * 50 + 25, 2), 'Specializes in outdoor cleaning and maintenance for decks and patios.', 11, 1),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in installing and repairing cabinetry for kitchens and bathrooms.', 12, 2),
       (ROUND(RAND() * 50 + 25, 2), 'Fence and gate repair specialist who can enhance your home security.', 13, 3),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in wallpaper removal and installation for a refreshed look.', 14, 4),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in the installation and setup of major household appliances.', 15, 5),
       (ROUND(RAND() * 50 + 25, 2), 'Comprehensive home cleaning services with great attention to detail.', 16, 1),
       (ROUND(RAND() * 50 + 25, 2), 'Professional garage organizer who can sort, clean, and declutter spaces.', 17, 2),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled at installing and replacing windows for improved home efficiency.', 18, 3),
       (ROUND(RAND() * 50 + 25, 2), 'Offers power washing services to restore the look of outdoor spaces.', 19, 4),
       (ROUND(RAND() * 50 + 25, 2), 'Professional tile installer for kitchens, bathrooms, and other spaces.', 20, 5),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in drywall installation and repair for a smooth finish.', 21, 6),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in tile and grout installation for kitchens and bathrooms.', 20, 6),
       (ROUND(RAND() * 50 + 25, 2), 'Proficient in installing and repairing hardwood and laminate flooring.', 10, 6),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in exterior siding installation for improved home protection.', 1, 6),
       (ROUND(RAND() * 50 + 25, 2), 'Specializes in deck construction and repair for outdoor living spaces.', 13, 6),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in crown molding installation for an elegant touch.', 7, 6),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced plumber capable of handling various plumbing installation and repair tasks.', 4, 7),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced carpenter skilled in custom furniture and cabinetry construction.', 12, 8),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in door and window frame installation and repair.', 18, 8),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in kitchen remodeling, including cabinet installation and countertop replacement.', 12, 9),
       (ROUND(RAND() * 50 + 25, 2), 'Proficient in bathroom renovation, including tile installation and fixture replacement.', 20, 9),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in plumbing and electrical work for remodeling projects.', 4, 9),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in flooring replacement and refinishing.', 10, 9),
       (ROUND(RAND() * 50 + 25, 2), 'Proficient in window installation and replacement.', 18, 10),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in lawn mowing, trimming, and edging for a well-manicured yard.', 5, 11),
       (ROUND(RAND() * 50 + 25, 2), 'Proficient in irrigation system installation and repair.', 4, 11),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in landscape lighting installation for enhanced aesthetics and security.', 3, 11),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in patio and walkway construction using a variety of materials.', 11, 11),
       (ROUND(RAND() * 50 + 25, 2), 'Proficient in closet and storage system installation.', 21, 12),
       (ROUND(RAND() * 50 + 25, 2), 'Specializes in garage organization and storage solutions.', 17, 12),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in interior painting using high-quality paints and finishes.', 2, 13),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in wallpaper installation for a personalized touch.', 14, 13),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in deck and fence staining and sealing for protection and longevity.', 13, 13),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced electrician offering electrical installation and repair services.', 3, 14),
       (ROUND(RAND() * 50 + 25, 2), 'Proficient in lighting fixture installation and replacement.', 3, 14),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced handyman offering general home repair and maintenance services.', 15, 15),
       (ROUND(RAND() * 50 + 25, 2), 'Proficient in furniture assembly and installation.', 7, 15),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in drywall repair and patching.', 2, 15),
       (ROUND(RAND() * 50 + 25, 2), 'Specializes in door and window repair and installation.', 18, 15),
       (ROUND(RAND() * 50 + 25, 2), 'Offers TV mounting and wire management services.', 8, 15),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced flooring installer specializing in hardwood, laminate, and tile floors.', 10, 16),
       (ROUND(RAND() * 50 + 25, 2), 'Proficient in floor refinishing and restoration.', 20, 16),
       (ROUND(RAND() * 50 + 25, 2), 'Specializes in tile and grout installation and repair.', 20, 16),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced carpenter offering custom woodworking and furniture construction.', 7, 17),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in custom cabinetry design and installation.', 12, 17),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced fence installer offering various fencing options for security and privacy.', 13, 18),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in fence staining and sealing for protection and longevity.', 1, 18),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced wallpaper specialist providing professional wallpaper removal and installation services.', 14, 19),
       (ROUND(RAND() * 50 + 25, 2), 'Proficient in wall surface preparation and repair.', 2, 19),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced HVAC technician offering installation, maintenance, and repair services.', 15, 20),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in window measurement and customization for a perfect fit.', 18, 21),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in plumbing fixture installation and repair.', 4, 22),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in air duct cleaning and maintenance.', 21, 23),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced kitchen remodeler offering full-service kitchen remodeling solutions.', 2, 24),
       (ROUND(RAND() * 50 + 25, 2), 'Proficient in bathroom remodeling, delivering functional and stylish designs.', 4, 24),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in custom cabinet installation and woodworking.', 12, 24),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in tile backsplash installation for a polished look.', 20, 24),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced carpenter offering custom woodworking and furniture construction.', 7, 25),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in custom cabinetry design and installation.', 12, 25),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced in basement finishing and remodeling.', 16, 26),
       (ROUND(RAND() * 50 + 25, 2), 'Specializes in roof ventilation and insulation.', 21, 27),
       (ROUND(RAND() * 50 + 25, 2), 'Specializes in tile and grout installation and repair.', 20, 28),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced drywall contractor offering installation and repair services.', 2, 29),
       (ROUND(RAND() * 50 + 25, 2), 'Experienced landscaper offering landscape design and installation services.', 5, 30),
       (ROUND(RAND() * 50 + 25, 2), 'Proficient in garden maintenance and lawn care.', 11, 30),
       (ROUND(RAND() * 50 + 25, 2), 'Skilled in irrigation system installation and repair.', 4, 30);


INSERT INTO tasks (task_details, date_assigned, time_start, budgeted_duration, date_completed, is_completed, is_accepted, user_id, honeydoer_service_id)
VALUES ('Paint exterior fence', '2023-06-02', '09:00', 4, NULL, 1, 1, 1, 1),
       ('Paint living room', '2023-06-02', '10:30', 3, NULL, 1, 1, 2, 2),
       ('Install new ceiling fan', '2023-06-02', '13:00', 2, NULL, 1, 1, 3, 3),
       ('Replace bathroom sink', '2023-06-02', '14:30', 1, NULL, 1, 1, 4, 4),
       ('Landscaping front yard', '2023-06-02', '08:00', 6, NULL, 1, 1, 5, 5),
       ('Move furniture to storage', '2023-06-02', '11:00', 3, NULL, 1, 1, 6, 6),
       ('Assemble new dining set', '2023-06-02', '12:30', 2, NULL, 1, 1, 7, 7),
       ('Mount TV in living room', '2023-06-02', '15:00', 1, NULL, 1, 1, 8, 8),
       ('Clean gutters', '2023-06-02', '09:30', 2, NULL, 1, 1, 9, 9),
       ('Install laminate flooring in kitchen', '2023-06-02', '13:30', 5, NULL, 1, 1, 10, 10),
       ('Power wash deck', '2023-06-02', '11:30', 3, NULL, 1, 1, 11, 11),
       ('Install kitchen cabinets', '2023-06-02', '09:00', 4, '2023-06-02', 1, 1, 12, 12),
       ('Repair backyard fence', '2023-06-02', '12:00', 3, NULL, 1, 1, 13, 13),
       ('Remove wallpaper in guest room', '2023-06-02', '14:30', 2, NULL, 1, 1, 14, 14),
       ('Install dishwasher', '2023-06-02', '10:00', 4, NULL, 1, 1, 15, 15),
       ('Clean entire house', '2023-06-02', '11:30', 5, NULL, 1, 1, 16, 16),
       ('Organize garage', '2023-06-02', '13:00', 2, NULL, 1, 1, 17, 17),
       ('Replace living room window', '2023-06-02', '09:00', 4, '2023-06-02', 1, 1, 18, 18),
       ('Power wash driveway', '2023-06-02', '14:00', 3, NULL, 1, 1, 19, 19),
       ('Install tile in bathroom', '2023-06-02', '10:30', 2, NULL, 1, 1, 20, 20);


INSERT INTO task_costs (honeydoer_pay, site_pay, total_user_cost, taxes, task_id)
VALUES (80, 16, 102.6, 6.6, 1),
       (150, 30, 193.875, 13.875, 2),
       (100, 20, 128.5, 8.5, 3),
       (120, 24, 154.2, 10.2, 4),
       (180, 36, 231.45, 15.45, 5),
       (70, 14, 90.775, 6.775, 6),
       (50, 10, 65.375, 5.375, 7),
       (100, 20, 128.5, 8.5, 8),
       (60, 12, 77.7, 5.7, 9),
       (200, 40, 257, 17, 10),
       (75, 15, 96.5625, 6.5625, 11),
       (150, 30, 193.875, 13.875, 12),
       (100, 20, 128.5, 8.5, 13),
       (80, 16, 102.6, 6.6, 14),
       (180, 36, 231.45, 15.45, 15),
       (70, 14, 90.775, 6.775, 16),
       (60, 12, 77.7, 5.7, 17),
       (160, 32, 205.2, 13.2, 18),
       (90, 18, 115.425, 7.425, 19),
       (200, 40, 257, 17, 20);


INSERT INTO honeydoer_reviews (stars, comment, task_id, honeydoer_id)
VALUES ('FIVE', 'Excellent work on painting the fence. Highly recommended.', 1, 1),
       ('FOUR', 'Very good job on painting the living room, but a bit slow.', 2, 2),
       ('THREE', 'Mediocre.', 2, 2),
       ('FIVE', 'Super duper great.', 2, 2),
       ('FIVE', 'The very best that no one ever was.', 2, 2),
       ('ONE', 'The worst.', 2, 2),
       ('THREE', 'Installation of the ceiling fan was okay, but not great.', 3, 3),
       ('FOUR', 'Good work on replacing the bathroom sink.', 4, 4),
       ('FIVE', 'Fantastic landscaping job in the front yard!', 5, 5),
       ('FOUR', 'Good job on moving the furniture, but arrived late.', 6, 6),
       ('FIVE', 'Did an excellent job assembling the new dining set.', 7, 7),
       ('FOUR', 'Good work on mounting the TV, but missed a step in the manual.', 8, 8),
       ('FIVE', 'Did a great job cleaning the gutters.', 9, 9),
       ('THREE', 'Flooring installation was average, not as good as expected.', 10, 10),
       ('FOUR', 'Deck looks much better after the power wash.', 11, 11),
       ('FIVE', 'Installed the kitchen cabinets perfectly!', 12, 12),
       ('FOUR', 'Fence repair was good, but left a small mess in the yard.', 13, 13),
       ('FOUR', 'Removal of wallpaper was done well, but took longer than estimated.', 14, 14),
       ('FIVE', 'Installed the dishwasher quickly and efficiently.', 15, 15),
       ('THREE', 'House cleaning was average, missed some areas.', 16, 16),
       ('FIVE', 'Organized the garage beautifully! Very pleased with the result.', 17, 17),
       ('FOUR', 'Did a good job replacing the window.', 18, 18),
       ('FOUR', 'Driveway looks cleaner after the power wash.', 19, 19),
       ('FIVE', 'Excellent tile installation in the bathroom.', 20, 20);


INSERT INTO client_reviews (stars, comment, task_id, user_id)
VALUES ('FIVE', 'Very responsible and respectful client.', 1, 1),
       ('FOUR', 'Good client but needed more clarity in task description.', 2, 2),
       ('THREE', 'Client was difficult to work with.', 3, 3),
       ('FOUR', 'Overall a pleasant experience working with this client.', 4, 4),
       ('FIVE', 'Excellent client! Clear instructions and prompt payment.', 5, 5),
       ('FOUR', 'Good client but there were delays in communication.', 6, 6),
       ('FIVE', 'Amazing client! Would love to work again with them.', 7, 7),
       ('FOUR', 'Client was good but there were some issues with payment.', 8, 8),
       ('FIVE', 'Client was understanding and easy to work with.', 9, 9),
       ('THREE', 'Had difficulties understanding client’s expectations.', 10, 10),
       ('FOUR', 'Good client, but there were issues with task scheduling.', 11, 11),
       ('FIVE', 'Great client! Clear instructions and easy communication.', 12, 12),
       ('FOUR', 'Client was good, but there were some last minute changes.', 13, 13),
       ('FOUR', 'Client was good but had unrealistic expectations.', 14, 14),
       ('FIVE', 'Excellent client! Very professional and understanding.', 15, 15),
       ('THREE', 'Client was difficult to communicate with.', 16, 16),
       ('FIVE', 'Great client! Always available for clarifications.', 17, 17),
       ('FOUR', 'Good client but needs to work on their communication.', 18, 18),
       ('FOUR', 'Client was good but had some issues with payment.', 19, 19),
       ('FIVE', 'Excellent client! Very clear and concise instructions.', 20, 20);

